POST http://localhost:3001/api/quotes
Content-Type: application/json

{
  "name": "Old Man",
  "text": "It's dangerous to go alone, take this!",
  "gameTitle": "The Legend of Zelda",
  "year": "1986"
}