POST http://localhost:3001/api/quotes
Content-Type: application/json

{
  "name": "Old Man",
  "quoteText": "It's dangerous to go alone, take this!",
  "title": "The Legend of Zelda",
  "year": "1986"
}